conversor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name='conversor'
urlpatterns = [
    path('converter/', views.converter_video, name='converter_video'),
    path('sucesso/', views.sucesso, name='sucesso'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversor_video_mp3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('conversor/',include('conversor.urls')),
]

conversor/models.py
from django.db import models

class Video(models.Model):
    arquivo = models.FileField(upload_to='videos/')
    data_envio = models.DateTimeField(auto_now_add=True)

class Audio(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    arquivo = models.FileField(upload_to='audios/')
    data_criacao = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Áudio para {self.video}'

conversor/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['arquivo']

conversor/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .forms import VideoForm
from .models import Video, Audio
from pydub import AudioSegment
import os

def converter_video(request):
    nome_arquivo = None
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save()
            caminho_video = video.arquivo.path
            nome_arquivo, _ = os.path.splitext(video.arquivo.name)
            caminho_audio = os.path.join(settings.MEDIA_ROOT, 'audios/videos', f'{nome_arquivo}.mp3')

            # Verifica se o diretório existe, caso contrário, cria
            diretorio_audio = os.path.dirname(caminho_audio)
            if not os.path.exists(diretorio_audio):
                os.makedirs(diretorio_audio)

            # Conversão do vídeo para áudio
            audio = AudioSegment.from_file(caminho_video)
            audio.export(caminho_audio, format='mp3')

            # Salvando o áudio no modelo
            Audio.objects.create(video=video, arquivo=caminho_audio)

            nome_arquivo = f'audios/videos/{nome_arquivo}.mp3'
            return render(request, 'conversor/sucesso.html', {'nome_arquivo': nome_arquivo})
    else:
        form = VideoForm()
    return render(request, 'conversor/converter.html', {'form': form})

def sucesso(request):
    return render(request, 'conversor/sucesso.html', {'MEDIA_URL': settings.MEDIA_URL})

conversor/templates/conversor/base_generic.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Conversor de Vídeos{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'conversor:converter_video' %}">Converter Vídeo</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>© 2024 Conversor de Vídeos. Todos os direitos reservados.</p>
    </footer>
</body>
</html>

conversor/templates/conversor/converter.html
{% extends 'conversor/base_generic.html' %}

{% block title %}
Converter Vídeo - Conversor de Vídeos
{% endblock %}

{% block content %}
    <h1>Converter Vídeo</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Converter</button>
    </form>
{% endblock %}

conversor/templates/conversor/sucesso.html
{% extends 'conversor/base_generic.html' %}

{% block title %}
Conversão Bem-Sucedida - Conversor de Vídeos
{% endblock %}

{% block content %}
    <h1>Seu vídeo foi convertido com sucesso!</h1>
    <p>Nome do arquivo convertido: {{ nome_arquivo }}</p>
    <a href="/conversor/media/{{ nome_arquivo }}">Baixar</a>
    <a href="{% url 'conversor:converter_video' %}">Converter outro vídeo</a>
{% endblock %}